// <auto-generated />
using System;
using AssetTracking.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTracking.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetTracking.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("WarrantyExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("Type").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AssetTracking.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USD",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EUR",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SEK",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CHF",
                            Symbol = "Fr"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TRY",
                            Symbol = "₺"
                        });
                });

            modelBuilder.Entity("AssetTracking.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CurrencyId = 1,
                            Name = "Lexicon USA"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Sweden",
                            CurrencyId = 2,
                            Name = "Lexicon Germany"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Sweden",
                            CurrencyId = 3,
                            Name = "Lexicon Sweden"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Switzerland",
                            CurrencyId = 4,
                            Name = "Lexicon Switzerland"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Türkiye",
                            CurrencyId = 5,
                            Name = "Lexicon Türkiye"
                        });
                });

            modelBuilder.Entity("AssetTracking.Models.ComputerAsset", b =>
                {
                    b.HasBaseType("AssetTracking.Models.Asset");

                    b.HasDiscriminator().HasValue("Computer");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Brand = "Dell",
                            Model = "Desktop 900",
                            OfficeId = 1,
                            Price = 100.0,
                            PurchaseDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-9",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Dell",
                            Model = "Desktop 900",
                            OfficeId = 1,
                            Price = 100.0,
                            PurchaseDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-10",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Lenovo",
                            Model = "X100",
                            OfficeId = 1,
                            Price = 300.0,
                            PurchaseDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-11",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Lenovo",
                            Model = "X200",
                            OfficeId = 1,
                            Price = 300.0,
                            PurchaseDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-12",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Lenovo",
                            Model = "X300",
                            OfficeId = 1,
                            Price = 500.0,
                            PurchaseDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-13",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2027, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            Model = "Optiplex 100",
                            OfficeId = 3,
                            Price = 1500.0,
                            PurchaseDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-14",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Dell",
                            Model = "Optiplex 200",
                            OfficeId = 3,
                            Price = 1400.0,
                            PurchaseDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-15",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2027, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Dell",
                            Model = "Optiplex 300",
                            OfficeId = 3,
                            Price = 1300.0,
                            PurchaseDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-16",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2027, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Asus",
                            Model = "ROG 600",
                            OfficeId = 2,
                            Price = 1600.0,
                            PurchaseDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-17",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2027, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 2,
                            Price = 1200.0,
                            PurchaseDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-18",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 2,
                            Price = 1200.0,
                            PurchaseDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-19",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Asus",
                            Model = "ROG 500",
                            OfficeId = 2,
                            Price = 1300.0,
                            PurchaseDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-CMP-20",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AssetTracking.Models.MobileAsset", b =>
                {
                    b.HasBaseType("AssetTracking.Models.Asset");

                    b.HasDiscriminator().HasValue("Mobile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Motorola",
                            Model = "X3",
                            OfficeId = 1,
                            Price = 200.0,
                            PurchaseDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-1",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Motorola",
                            Model = "X3",
                            OfficeId = 1,
                            Price = 400.0,
                            PurchaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-2",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Motorola",
                            Model = "X2",
                            OfficeId = 1,
                            Price = 400.0,
                            PurchaseDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-3",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            Model = "Galaxy 10",
                            OfficeId = 3,
                            Price = 4500.0,
                            PurchaseDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-4",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            Model = "Galaxy 10",
                            OfficeId = 3,
                            Price = 4500.0,
                            PurchaseDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-5",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Sony",
                            Model = "XPeria 7",
                            OfficeId = 3,
                            Price = 3000.0,
                            PurchaseDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-6",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Sony",
                            Model = "XPeria 7",
                            OfficeId = 3,
                            Price = 3000.0,
                            PurchaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-7",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Siemens",
                            Model = "Brick",
                            OfficeId = 2,
                            Price = 220.0,
                            PurchaseDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-8",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2027, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Motorola",
                            Model = "X4",
                            OfficeId = 4,
                            Price = 400.0,
                            PurchaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SR-MBL-21",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AssetTracking.Models.Asset", b =>
                {
                    b.HasOne("AssetTracking.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("AssetTracking.Models.Office", b =>
                {
                    b.HasOne("AssetTracking.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
